model_class = "FasterWhisperTranscriber"

schema_id = "open/audio-transcription"
schema_version = "0.4.0"

[[dependencies]]
type = "media_type"
include = ["audio", "video"]

[options]
model_size = "base"
